// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: protobuf_files/systemicdb.proto

package systemicdbGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetByKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Datum         string `protobuf:"bytes,2,opt,name=datum,proto3" json:"datum,omitempty"`
	ExpirySeconds int32  `protobuf:"varint,3,opt,name=expirySeconds,proto3" json:"expirySeconds,omitempty"`
}

func (x *SetByKeyRequest) Reset() {
	*x = SetByKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_files_systemicdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetByKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetByKeyRequest) ProtoMessage() {}

func (x *SetByKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_files_systemicdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetByKeyRequest.ProtoReflect.Descriptor instead.
func (*SetByKeyRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_files_systemicdb_proto_rawDescGZIP(), []int{0}
}

func (x *SetByKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetByKeyRequest) GetDatum() string {
	if x != nil {
		return x.Datum
	}
	return ""
}

func (x *SetByKeyRequest) GetExpirySeconds() int32 {
	if x != nil {
		return x.ExpirySeconds
	}
	return 0
}

type SetByTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag           string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Datum         string `protobuf:"bytes,3,opt,name=datum,proto3" json:"datum,omitempty"`
	ExpirySeconds int32  `protobuf:"varint,4,opt,name=expirySeconds,proto3" json:"expirySeconds,omitempty"`
}

func (x *SetByTagRequest) Reset() {
	*x = SetByTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_files_systemicdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetByTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetByTagRequest) ProtoMessage() {}

func (x *SetByTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_files_systemicdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetByTagRequest.ProtoReflect.Descriptor instead.
func (*SetByTagRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_files_systemicdb_proto_rawDescGZIP(), []int{1}
}

func (x *SetByTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SetByTagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetByTagRequest) GetDatum() string {
	if x != nil {
		return x.Datum
	}
	return ""
}

func (x *SetByTagRequest) GetExpirySeconds() int32 {
	if x != nil {
		return x.ExpirySeconds
	}
	return 0
}

type GetByKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetByKeyRequest) Reset() {
	*x = GetByKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_files_systemicdb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByKeyRequest) ProtoMessage() {}

func (x *GetByKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_files_systemicdb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByKeyRequest.ProtoReflect.Descriptor instead.
func (*GetByKeyRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_files_systemicdb_proto_rawDescGZIP(), []int{2}
}

func (x *GetByKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetByTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *GetByTagRequest) Reset() {
	*x = GetByTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_files_systemicdb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByTagRequest) ProtoMessage() {}

func (x *GetByTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_files_systemicdb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByTagRequest.ProtoReflect.Descriptor instead.
func (*GetByTagRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_files_systemicdb_proto_rawDescGZIP(), []int{3}
}

func (x *GetByTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type SingleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datum string `protobuf:"bytes,1,opt,name=datum,proto3" json:"datum,omitempty"`
}

func (x *SingleResponse) Reset() {
	*x = SingleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_files_systemicdb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleResponse) ProtoMessage() {}

func (x *SingleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_files_systemicdb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleResponse.ProtoReflect.Descriptor instead.
func (*SingleResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_files_systemicdb_proto_rawDescGZIP(), []int{4}
}

func (x *SingleResponse) GetDatum() string {
	if x != nil {
		return x.Datum
	}
	return ""
}

type RepeatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datum []string `protobuf:"bytes,1,rep,name=datum,proto3" json:"datum,omitempty"`
}

func (x *RepeatedResponse) Reset() {
	*x = RepeatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_files_systemicdb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedResponse) ProtoMessage() {}

func (x *RepeatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_files_systemicdb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedResponse.ProtoReflect.Descriptor instead.
func (*RepeatedResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_files_systemicdb_proto_rawDescGZIP(), []int{5}
}

func (x *RepeatedResponse) GetDatum() []string {
	if x != nil {
		return x.Datum
	}
	return nil
}

type BoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_files_systemicdb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_files_systemicdb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_files_systemicdb_proto_rawDescGZIP(), []int{6}
}

func (x *BoolResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_protobuf_files_systemicdb_proto protoreflect.FileDescriptor

var file_protobuf_files_systemicdb_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x47, 0x72, 0x70,
	0x63, 0x22, 0x5f, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x75, 0x6d, 0x12, 0x24, 0x0a, 0x0d,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x22, 0x71, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74,
	0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x75, 0x6d, 0x12,
	0x24, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x79, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22,
	0x26, 0x0a, 0x0e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x64, 0x61, 0x74, 0x75, 0x6d, 0x22, 0x28, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x61, 0x74, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x75,
	0x6d, 0x22, 0x1e, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x32, 0x9f, 0x01, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x4a, 0x0a, 0x05, 0x42, 0x79, 0x4b,
	0x65, 0x79, 0x12, 0x1f, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x47,
	0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62,
	0x47, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x05, 0x42, 0x79, 0x54, 0x61, 0x67, 0x12, 0x1f,
	0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x47, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x32, 0x99, 0x01, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x48, 0x0a, 0x05, 0x42,
	0x79, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64,
	0x62, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63,
	0x64, 0x62, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x05, 0x42, 0x79, 0x54, 0x61, 0x67, 0x12, 0x1f,
	0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x65, 0x74, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x47, 0x72, 0x70, 0x63,
	0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32,
	0x99, 0x01, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x48, 0x0a, 0x05, 0x42, 0x79, 0x4b, 0x65, 0x79,
	0x12, 0x1f, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x47, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x47, 0x72,
	0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x48, 0x0a, 0x05, 0x42, 0x79, 0x54, 0x61, 0x67, 0x12, 0x1f, 0x2e, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x64, 0x62, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x61, 0x6d, 0x75, 0x65, 0x6c,
	0x42, 0x61, 0x6e, 0x6b, 0x73, 0x54, 0x65, 0x63, 0x68, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x69, 0x63, 0x64, 0x62, 0x47, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_files_systemicdb_proto_rawDescOnce sync.Once
	file_protobuf_files_systemicdb_proto_rawDescData = file_protobuf_files_systemicdb_proto_rawDesc
)

func file_protobuf_files_systemicdb_proto_rawDescGZIP() []byte {
	file_protobuf_files_systemicdb_proto_rawDescOnce.Do(func() {
		file_protobuf_files_systemicdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_files_systemicdb_proto_rawDescData)
	})
	return file_protobuf_files_systemicdb_proto_rawDescData
}

var file_protobuf_files_systemicdb_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protobuf_files_systemicdb_proto_goTypes = []interface{}{
	(*SetByKeyRequest)(nil),  // 0: systemicdbGrpc.SetByKeyRequest
	(*SetByTagRequest)(nil),  // 1: systemicdbGrpc.SetByTagRequest
	(*GetByKeyRequest)(nil),  // 2: systemicdbGrpc.GetByKeyRequest
	(*GetByTagRequest)(nil),  // 3: systemicdbGrpc.GetByTagRequest
	(*SingleResponse)(nil),   // 4: systemicdbGrpc.SingleResponse
	(*RepeatedResponse)(nil), // 5: systemicdbGrpc.RepeatedResponse
	(*BoolResponse)(nil),     // 6: systemicdbGrpc.BoolResponse
}
var file_protobuf_files_systemicdb_proto_depIdxs = []int32{
	2, // 0: systemicdbGrpc.Get.ByKey:input_type -> systemicdbGrpc.GetByKeyRequest
	3, // 1: systemicdbGrpc.Get.ByTag:input_type -> systemicdbGrpc.GetByTagRequest
	0, // 2: systemicdbGrpc.Set.ByKey:input_type -> systemicdbGrpc.SetByKeyRequest
	1, // 3: systemicdbGrpc.Set.ByTag:input_type -> systemicdbGrpc.SetByTagRequest
	2, // 4: systemicdbGrpc.Del.ByKey:input_type -> systemicdbGrpc.GetByKeyRequest
	3, // 5: systemicdbGrpc.Del.ByTag:input_type -> systemicdbGrpc.GetByTagRequest
	4, // 6: systemicdbGrpc.Get.ByKey:output_type -> systemicdbGrpc.SingleResponse
	5, // 7: systemicdbGrpc.Get.ByTag:output_type -> systemicdbGrpc.RepeatedResponse
	6, // 8: systemicdbGrpc.Set.ByKey:output_type -> systemicdbGrpc.BoolResponse
	6, // 9: systemicdbGrpc.Set.ByTag:output_type -> systemicdbGrpc.BoolResponse
	6, // 10: systemicdbGrpc.Del.ByKey:output_type -> systemicdbGrpc.BoolResponse
	6, // 11: systemicdbGrpc.Del.ByTag:output_type -> systemicdbGrpc.BoolResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_files_systemicdb_proto_init() }
func file_protobuf_files_systemicdb_proto_init() {
	if File_protobuf_files_systemicdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_files_systemicdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetByKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_files_systemicdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetByTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_files_systemicdb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_files_systemicdb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_files_systemicdb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_files_systemicdb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_files_systemicdb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_files_systemicdb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_protobuf_files_systemicdb_proto_goTypes,
		DependencyIndexes: file_protobuf_files_systemicdb_proto_depIdxs,
		MessageInfos:      file_protobuf_files_systemicdb_proto_msgTypes,
	}.Build()
	File_protobuf_files_systemicdb_proto = out.File
	file_protobuf_files_systemicdb_proto_rawDesc = nil
	file_protobuf_files_systemicdb_proto_goTypes = nil
	file_protobuf_files_systemicdb_proto_depIdxs = nil
}
